export const data = [{id: 2, name: "Currry Powder", category: "Dry Goods", size: "Bag", price: 3, par: 10, "on hand":"", "to order": ""},
{id: 3, name: "Basil", category: "Herbs", size: "Bunch", price: 2, par: 10, "on hand":"", "to order": ""},
{id: 4, name: "Thyme", category: "Herbs", size: "Bunch", price: 2, par: 10, "on hand":"", "to order": ""},
{id: 5, name: "Sage", category: "Herbs", size: "Bunch", price: 2, par: 10, "on hand":"", "to order": ""},
{id: 6, name: "Oregano", category: "Herbs", size: "Bunch", price: 2, par: 10, "on hand":"", "to order": ""},
{id: 7, name: "Parsley", category: "Herbs", size: "Bunch", price: 2, par: 10, "on hand":"", "to order": ""},
{id: 8, name: "Rosemary", category: "Herbs", size: "Bunch", price: 2, par: 10, "on hand":"", "to order": ""},
{id: 9, name: "Kale", category: "Produce", size: "Bunch", price: 3, par: 10, "on hand":"", "to order": ""},
{id: 10, name: "Iceberg Lettuce", category: "Produce", size: "Head", price: 3, par: 10, "on hand":"", "to order": ""},
{id: 11, name: "Broccoli", category: "Produce", size: "Head", price: 3, par: 10, "on hand":"", "to order": ""},
{id: 12, name: "Tomatoe", category: "Produce", size: "Individual", price: 2, par: 10, "on hand":"", "to order": ""},
{id: 13, name: "Celery", category: "Produce", size: "Bunch", price: 1, par: 10, "on hand":"", "to order": ""},
{id: 14, name: "Leeks", category: "Produce", size: "Individual", price: 1, par: 10, "on hand":"", "to order": ""},
{id: 15, name: "Potatoe", category: "Produce", size: "5lbs bag", price: 5, par: 10, "on hand":"", "to order": ""},
{id: 16, name: "Yam", category: "Produce", size: "5lbs bag", price: 5, par: 10, "on hand":"", "to order": ""},
{id: 17, name: "Eggplant", category: "Produce", size: "Individual", price: 1, par: 10, "on hand":"", "to order": ""},
{id: 18, name: "Carrot", category: "Produce", size: "1 lbs bag", price: 3, par: 10, "on hand":"", "to order": ""},
{id: 19, name: "Peas", category: "Produce", size: "1 lbs bag", price: 2, par: 10, "on hand":"", "to order": ""},
{id: 20, name: "Salmon Fillet", category: "Meat", size: "Individual", price: 5, par: 10, "on hand":"", "to order": ""},
{id: 21, name: "Beef Brisket", category: "Meat", size: "Individual", price: 8, par: 10, "on hand":"", "to order": ""},
{id: 22, name: "Pork Shoulder", category: "Meat", size: "Individual", price: 8, par: 10, "on hand":"", "to order": ""},
{id: 23, name: "Chicken Breast", category: "Meat", size: "Individual", price: 5, par: 10, "on hand":"", "to order": ""},
{id: 24, name: "Currry Powder", category: "Dry Goods", size: "Bag", price: 3, par: 10, "on hand":"", "to order": ""},
{id: 25, name: "Basil", category: "Herbs", size: "Bunch", price: 2, par: 10, "on hand":"", "to order": ""},
{id: 26, name: "Thyme", category: "Herbs", size: "Bunch", price: 2, par: 10, "on hand":"", "to order": ""},
{id: 27, name: "Sage", category: "Herbs", size: "Bunch", price: 2, par: 10, "on hand":"", "to order": ""},
{id: 28, name: "Oregano", category: "Herbs", size: "Bunch", price: 2, par: 10, "on hand":"", "to order": ""},
{id: 29, name: "Parsley", category: "Herbs", size: "Bunch", price: 2, par: 10, "on hand":"", "to order": ""},
{id: 30, name: "Rosemary", category: "Herbs", size: "Bunch", price: 2, par: 10, "on hand":"", "to order": ""},
{id: 31, name: "Kale", category: "Produce", size: "Bunch", price: 3, par: 10, "on hand":"", "to order": ""},
{id: 32, name: "Iceberg Lettuce", category: "Produce", size: "Head", price: 3, par: 10, "on hand":"", "to order": ""},
{id: 33, name: "Broccoli", category: "Produce", size: "Head", price: 3, par: 10, "on hand":"", "to order": ""},
{id: 34, name: "Tomatoe", category: "Produce", size: "Individual", price: 2, par: 10, "on hand":"", "to order": ""},
{id: 35, name: "Celery", category: "Produce", size: "Bunch", price: 1, par: 10, "on hand":"", "to order": ""},
{id: 36, name: "Leeks", category: "Produce", size: "Individual", price: 1, par: 10, "on hand":"", "to order": ""},
{id: 37, name: "Potatoe", category: "Produce", size: "5lbs bag", price: 5, par: 10, "on hand":"", "to order": ""},
{id: 38, name: "Yam", category: "Produce", size: "5lbs bag", price: 5, par: 10, "on hand":"", "to order": ""},
{id: 39, name: "Eggplant", category: "Produce", size: "Individual", price: 1, par: 10, "on hand":"", "to order": ""},
{id: 40, name: "Carrot", category: "Produce", size: "1 lbs bag", price: 3, par: 10, "on hand":"", "to order": ""},
{id: 41, name: "Peas", category: "Produce", size: "1 lbs bag", price: 2, par: 10, "on hand":"", "to order": ""},
{id: 42, name: "Salmon Fillet", category: "Meat", size: "Individual", price: 5, par: 10, "on hand":"", "to order": ""},
{id: 43, name: "Beef Brisket", category: "Meat", size: "Individual", price: 8, par: 10, "on hand":"", "to order": ""},
{id: 44, name: "Pork Shoulder", category: "Meat", size: "Individual", price: 8, par: 10, "on hand":"", "to order": ""},
{id: 45, name: "Chicken Breast", category: "Meat", size: "Individual", price: 5, par: 10, "on hand":"", "to order": ""},
{id: 46, name: "Something Really Long for Testing Purposes", category: "Back Freezer Items ", size: "Test", price: 3, par: 10, "on hand":"", "to order": ""}]
